apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/alekseimelnikov/.minikube/ca.crt
    server: https://192.168.99.100:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: ""
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/alekseimelnikov/.minikube/profiles/minikube/client.crt
    client-key: /Users/alekseimelnikov/.minikube/profiles/minikube/client.key