apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitoring-daemon
  namespace: kube-system
spec:    
  selector:
    matchLabels:
      app: mon-agent
  template:
    metadata:       
      labels:
        app: mon-agent    
    spec:
      containers:
        - name: mon-agent
          image: mon-agent
    
