apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://<just_ip>
  name: gke_123
- cluster:
    certificate-authority: /Users/admin/.minikube/ca.crt
    server: https://<ip>:<port>
  name: minikube
contexts:
- context:
    cluster: gke_123
    user: gke_123
  name: gke_123
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: gke_123
kind: Config
preferences: {}
users:
- name: gke_123
  user:
    auth-provider:
      config:
        access-token: <token>
        cmd-args: config config-helper --format=json
        cmd-path: /Users/admin/Documents/google-cloud-sdk/bin/gcloud
        expiry: "2010-09-12T15:64:26Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: minikube
  user:
    client-certificate: /Users/admin/.minikube/profiles/minikube/client.crt
    client-key: /Users/admin/.minikube/profiles/minikube/client.key