apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp 
    type: front-end
spec:    
  selector:
    matchLabels:
      type: front-end
      app: myapp
  replicas: 6
  template:
    metadata: 
      name: nginx-2
      labels:
        app: myapp
        env: production
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx
    


